-- Run in Supabase SQL Editor - Migration 1 of 6
-- Creates role enum and user_roles table with RLS policies

-- Create role enum (Admin, Member)
create type public.app_role as enum ('admin', 'member');

-- User roles table
create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references auth.users on delete cascade not null,
  role      app_role not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique (user_id, role)
);

-- Enable RLS
alter table public.user_roles enable row level security;

-- Only admins can manage roles
create policy "Admins can manage user roles"
  on public.user_roles
  for all
  to authenticated
  using (
    exists (
      select 1 from public.user_roles ur
      where ur.user_id = auth.uid() and ur.role = 'admin'
    )
  );

-- All authenticated users can view roles
create policy "Users can view all roles"
  on public.user_roles
  for select
  to authenticated
  using (true);
