-- Run in Supabase SQL Editor - Migration 5 of 6
-- Creates application-level audit log table and triggers for business events

-- Application audit log table
create table if not exists public.app_audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  user_email text,
  event_type text not null,       -- 'role_change', 'settings_update', 'auth_event', etc.
  resource_type text,              -- 'user', 'investor', 'settings'
  resource_id text,
  action text not null,            -- 'create', 'update', 'delete', 'assign_role', etc.
  old_data jsonb,
  new_data jsonb,
  metadata jsonb,                  -- Additional context
  ip_address text,
  user_agent text,
  created_at timestamp with time zone default now()
);

-- Enable RLS on app_audit_log
alter table public.app_audit_log enable row level security;

-- All authenticated users can view audit logs (members have read-only per requirements)
create policy "All authenticated users can view audit logs"
  on public.app_audit_log
  for select
  to authenticated
  using (true);

-- System can insert audit logs
create policy "System can insert audit logs"
  on public.app_audit_log
  for insert
  to authenticated
  with check (true);

-- Function to log role changes
create or replace function public.log_role_change()
returns trigger
language plpgsql
security definer
as $$
declare
  actor_email text;
begin
  select email into actor_email from auth.users where id = auth.uid();

  if (TG_OP = 'INSERT') then
    insert into public.app_audit_log (
      user_id, user_email, event_type, resource_type,
      resource_id, action, new_data
    ) values (
      auth.uid(), actor_email, 'role_change', 'user',
      NEW.user_id::text, 'assign_role',
      jsonb_build_object('role', NEW.role)
    );
    return NEW;
  elsif (TG_OP = 'UPDATE') then
    insert into public.app_audit_log (
      user_id, user_email, event_type, resource_type,
      resource_id, action, old_data, new_data
    ) values (
      auth.uid(), actor_email, 'role_change', 'user',
      NEW.user_id::text, 'change_role',
      jsonb_build_object('role', OLD.role),
      jsonb_build_object('role', NEW.role)
    );
    return NEW;
  elsif (TG_OP = 'DELETE') then
    insert into public.app_audit_log (
      user_id, user_email, event_type, resource_type,
      resource_id, action, old_data
    ) values (
      auth.uid(), actor_email, 'role_change', 'user',
      OLD.user_id::text, 'remove_role',
      jsonb_build_object('role', OLD.role)
    );
    return OLD;
  end if;
end;
$$;

-- Trigger on user_roles table to log all role changes
create trigger user_roles_audit_trigger
  after insert or update or delete on public.user_roles
  for each row execute function public.log_role_change();
